package di5numeric;
import com.ochafik.lang.jnaerator.runtime.Structure;
/**
 * <i>native declaration : inc\numeric.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Numeric extends Structure<Numeric, Numeric.ByValue, Numeric.ByReference > {
	public Numeric() {
		super();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected Numeric newInstance() { return new Numeric(); }
	public static Numeric[] newArray(int arrayLength) {
		return Structure.newArray(Numeric.class, arrayLength);
	}
	public static class ByReference extends Numeric implements Structure.ByReference {
		
	};
	public static class ByValue extends Numeric implements Structure.ByValue {
		
	};
}
