package di5engine3;
import com.ochafik.lang.jnaerator.runtime.Structure;
/**
 * <i>native declaration : inc\rdi5api.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class D5FileInfo extends Structure<D5FileInfo, D5FileInfo.ByValue, D5FileInfo.ByReference > {
	/// < D5Dファイルを作成したOSタイプ
	public byte OSType;
	/// < D5Dファイルを作成したシステムのエンディアン・タイプ
	public byte Endian;
	/// < D5Dファイルを作成した際のLFMエンジンのビット数
	public byte ELF;
	/**
	 * < D5DファイルのDB文字コード<br>
	 * C type : char[32]
	 */
	public byte[] DBCharCode = new byte[(32)];
	/**
	 * < D5Dファイルのバージョン<br>
	 * C type : int[D5_VERSION_SIZE]
	 */
	public int[] Version = new int[(di5engine3.Di5Engine3Library.D5_VERSION_SIZE)];
	public D5FileInfo() {
		super();
	}
	/**
	 * @param OSType < D5Dファイルを作成したOSタイプ<br>
	 * @param Endian < D5Dファイルを作成したシステムのエンディアン・タイプ<br>
	 * @param ELF < D5Dファイルを作成した際のLFMエンジンのビット数<br>
	 * @param DBCharCode < D5DファイルのDB文字コード<br>
	 * C type : char[32]<br>
	 * @param Version < D5Dファイルのバージョン<br>
	 * C type : int[D5_VERSION_SIZE]
	 */
	public D5FileInfo(byte OSType, byte Endian, byte ELF, byte DBCharCode[], int Version[]) {
		super();
		this.OSType = OSType;
		this.Endian = Endian;
		this.ELF = ELF;
		if (DBCharCode.length != this.DBCharCode.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.DBCharCode = DBCharCode;
		if (Version.length != this.Version.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.Version = Version;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected D5FileInfo newInstance() { return new D5FileInfo(); }
	public static D5FileInfo[] newArray(int arrayLength) {
		return Structure.newArray(D5FileInfo.class, arrayLength);
	}
	public static class ByReference extends D5FileInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends D5FileInfo implements Structure.ByValue {
		
	};
}
