/*--------------------------------------------------------------------------
*
*       DI5 DLL ERROR CODE DEFINITION   
*             
*           (C)2001-2009 Turbo Data Laboratories, Inc.
* 
----------------------------------------------------------------------------*/
#ifndef _D5ERROR_H
#define _D5ERROR_H


// ------------- D5 ERROR CODE ------------
#define D5_CUSTOM_ERROR         (0xE0000000)

//=============== ARGUMENT RANGE ERROR ====================

#define D5_ERROR_INVALID_VALUE          (D5_CUSTOM_ERROR | 1L)
#define D5_ERROR_ILLEGAL_VALUE_ORDER    (D5_CUSTOM_ERROR | 2L)
#define	D5_ERROR_INNER_SYSTEM			(D5_CUSTOM_ERROR | 3L)
#define	D5_ERROR_DIR_NOTFOUND			(D5_CUSTOM_ERROR | 4L)
#define D5_ERROR_INVALID_WIDTH          (D5_CUSTOM_ERROR | 10L)
#define D5_ERROR_INVALID_ROW_SIZE       (D5_CUSTOM_ERROR | 12L)
#define D5_ERROR_TOO_LARGE_ROW_SIZE     (D5_CUSTOM_ERROR | 13L)
#define D5_ERROR_INVALID_ROW_INDEX      (D5_CUSTOM_ERROR | 14L)
#define D5_ERROR_ILLEGAL_ROW_ORDER      (D5_CUSTOM_ERROR | 15L)
#define D5_ERROR_INVALID_FILTER_SIZE    (D5_CUSTOM_ERROR | 16L)
#define D5_ERROR_TOO_LARGE_FILTER_SIZE  (D5_CUSTOM_ERROR | 17L)
#define D5_ERROR_INVALID_FILTER_INDEX   (D5_CUSTOM_ERROR | 18L)
#define D5_ERROR_ILLEGAL_FILTER_ORDER   (D5_CUSTOM_ERROR | 19L)
#define D5_ERROR_TOO_MANY_DATA          (D5_CUSTOM_ERROR | 21L)
#define D5_ERROR_TOO_LONG_STRING        (D5_CUSTOM_ERROR | 22L)
#define D5_ERROR_ILLEGAL_STRING_ORDER   (D5_CUSTOM_ERROR | 23L)
#define D5_ERROR_OUT_OF_MEMORY          (D5_CUSTOM_ERROR | 24L)
#define D5_ERROR_OUT_OF_SUMMARY_AREA    (D5_CUSTOM_ERROR | 25L)
#define D5_ERROR_INVALID_RANGE			(D5_CUSTOM_ERROR | 26L)
#define D5_ERROR_MEMORY_LIMIT_OVERFLOW	(D5_CUSTOM_ERROR | 27L)
#define D5_ERROR_TOO_MANY_USERS			(D5_CUSTOM_ERROR | 28L)


//=============== ARGUMENT ILLEGAL VALUE ====================

#define D5_ERROR_ILLEGAL_DATA_TYPE      (D5_CUSTOM_ERROR | 51L)
#define D5_ERROR_ILLEGAL_OPERATION      (D5_CUSTOM_ERROR | 52L)
#define D5_ERROR_ILLEGAL_TABLE_NAME     (D5_CUSTOM_ERROR | 53L)
#define D5_ERROR_ILLEGAL_FILTER_NAME    (D5_CUSTOM_ERROR | 54L)
#define D5_ERROR_ILLEGAL_TARGET         (D5_CUSTOM_ERROR | 55L)
#define D5_ERROR_INVALID_HANDLE			(D5_CUSTOM_ERROR | 57L)


//=============== OVERFLOW ERROR ====================

#define	D5_ERROR_OVERFLOW_TABLE         (D5_CUSTOM_ERROR | 99L)
#define D5_ERROR_OVERFLOW_REAL          (D5_CUSTOM_ERROR | 100L)
#define D5_ERROR_OVERFLOW_JOIN          (D5_CUSTOM_ERROR | 101L)
#define D5_ERROR_OVERFLOW_SET           (D5_CUSTOM_ERROR | 102L)
#define D5_ERROR_OVERFLOW_SLAVE         (D5_CUSTOM_ERROR | 103L)
#define D5_ERROR_TOO_LARGE_JOIN_TABLE   (D5_CUSTOM_ERROR | 104L)


//=============== ERROR CODE ====================

#define D5_ERROR_NO_DATA                (D5_CUSTOM_ERROR | 105L)
#define D5_ERROR_NO_FILTER              (D5_CUSTOM_ERROR | 106L)
#define D5_ERROR_NO_MASTER_FILTER       (D5_CUSTOM_ERROR | 107L)
#define D5_ERROR_NO_SLAVE_FILTER        (D5_CUSTOM_ERROR | 108L)
#define D5_ERROR_NO_TABLE               (D5_CUSTOM_ERROR | 109L)
#define D5_ERROR_NO_MASTER_TABLE        (D5_CUSTOM_ERROR | 110L)
#define D5_ERROR_NO_SLAVE_TABLE         (D5_CUSTOM_ERROR | 111L)
#define D5_ERROR_NO_JOIN_TABLE          (D5_CUSTOM_ERROR | 112L)
#define D5_ERROR_NO_SET                 (D5_CUSTOM_ERROR | 113L)
#define D5_ERROR_NO_MASTER_SET          (D5_CUSTOM_ERROR | 114L)
#define D5_ERROR_NO_SLAVE_SET           (D5_CUSTOM_ERROR | 115L)
#define D5_ERROR_INVALID_DATA_TYPE      (D5_CUSTOM_ERROR | 116L)
#define D5_ERROR_INVALID_DATA_SIZE      (D5_CUSTOM_ERROR | 117L)
#define D5_ERROR_INVALID_TABLE_TYPE     (D5_CUSTOM_ERROR | 118L)
#define D5_ERROR_INVALID_TABLE_SIZE     (D5_CUSTOM_ERROR | 119L)

#define D5_ERROR_INVALID_INDEX          (D5_CUSTOM_ERROR | 121L)
#define D5_ERROR_INVALID_SETID          (D5_CUSTOM_ERROR | 122L)
#define D5_ERROR_MISMATCH_DATA_SIZE     (D5_CUSTOM_ERROR | 123L)
#define D5_ERROR_MISMATCH_DATA_TYPE     (D5_CUSTOM_ERROR | 124L) 
#define D5_ERROR_MISMATCH_TABLE_TYPE    (D5_CUSTOM_ERROR | 126L)
#define	D5_ERROR_FILTER_COUNT			(D5_CUSTOM_ERROR | 127L)
#define	D5_ERROR_MISMATCH_FILTER		(D5_CUSTOM_ERROR | 128L)
#define	D5_ERROR_SET_UNASSIGNED			(D5_CUSTOM_ERROR | 129L)
#define	D5_ERROR_INVALID_PARAM			(D5_CUSTOM_ERROR | 130L)
#define	D5_ERROR_SUMMARY_NOT_MADE		(D5_CUSTOM_ERROR | 131L)

#define D5_ERROR_DUPLICATE_TABLE_NAME   (D5_CUSTOM_ERROR | 132L)
#define D5_ERROR_DUPLICATE_FILTER_NAME  (D5_CUSTOM_ERROR | 133L)
#define D5_ERROR_DELETE_ROOT_SET        (D5_CUSTOM_ERROR | 134L)
#define D5_ERROR_REFFERED_TABLE         (D5_CUSTOM_ERROR | 135L)
#define D5_ERROR_INVALID_FILTERID       (D5_CUSTOM_ERROR | 136L)
#define D5_ERROR_NO_REALTABLE           (D5_CUSTOM_ERROR | 137L)
#define D5_ERROR_NO_JOINTABLE           (D5_CUSTOM_ERROR | 138L)
#define	D5_ERROE_UNINIT_PARAM			(D5_CUSTOM_ERROR | 140L)
#define	D5_ERROR_FILE_IO				(D5_CUSTOM_ERROR | 141L)
#define	D5_ERROR_FILE_PATH				(D5_CUSTOM_ERROR | 142L)
#define D5_ERROR_NOT_TABLE_NAME			(D5_CUSTOM_ERROR | 143L)
#define D5_ERROR_NOT_INNERJOIN			(D5_CUSTOM_ERROR | 144L)
#define D5_ERROR_INVALID_TABLE_NAME		(D5_CUSTOM_ERROR | 145L)
#define	D5_ERROR_NOT_JOIN_CHAIN			(D5_CUSTOM_ERROR | 146L)
#define	D5_ERROR_MISMATCH_DATA			(D5_CUSTOM_ERROR | 147L)
#define	D5_ERROR_EMPTY_SET				(D5_CUSTOM_ERROR | 148L)
#define	D5_ERROR_DIR_ALREADY_EXIST		(D5_CUSTOM_ERROR | 149L)
#define	D5_ERROR_DIR_INVALID_PATH		(D5_CUSTOM_ERROR | 150L)
#define	D5_ERROR_DIR_NOT_EMPTY			(D5_CUSTOM_ERROR | 151L)
#define	D5_ERROR_ACCESS_DENIED			(D5_CUSTOM_ERROR | 152L)
#define D5_ERROR_ALREADY_CLOSED			(D5_CUSTOM_ERROR | 153L)
#define D5_ERROR_ALREADY_OPENED			(D5_CUSTOM_ERROR | 154L)
#define D5_ERROR_ALREADY_DONE			(D5_CUSTOM_ERROR | 155L)
#define D5_ERROR_DETAIL_NOT_MADE		(D5_CUSTOM_ERROR | 156L)



#define D5_ERROR_GET_PROJECTION         (D5_CUSTOM_ERROR | 202L)
#define D5_ERROR_ADDFILTER2             (D5_CUSTOM_ERROR | 204L)

#define D5_ERROR_SAVE_FILE_NAME         (D5_CUSTOM_ERROR | 205L)
#define D5_ERROR_DATA_VERSION           (D5_CUSTOM_ERROR | 206L)

#define	D5_ERROR_INVALID_OPERATION		(D5_CUSTOM_ERROR | 207L)
#define	D5_ERROR_INVALID_DATATABLE		(D5_CUSTOM_ERROR | 208L)
#define	D5_ERROR_INVALID_DIMSIZE		(D5_CUSTOM_ERROR | 209L)
#define	D5_ERROR_MEMORY_STREAM_CLOSE	(D5_CUSTOM_ERROR | 210L)

#define	D5_ERROR_FIND_NOT_OPEN			(D5_CUSTOM_ERROR | 220L)
#define	D5_ERROR_FIND_VERSION			(D5_CUSTOM_ERROR | 221L)

#define	D5_ERROR_CALC_TARGET_FILTER		(D5_CUSTOM_ERROR | 230L)
#define	D5_ERROR_NOT_NUMERICAL_FILTER	(D5_CUSTOM_ERROR | 231L)
#define	D5_ERROR_CALC_FILTER_AREA_OVERFLOW	(D5_CUSTOM_ERROR | 232L)
#define	D5_ERROR_CALC_CONST_AREA_OVERFLOW	(D5_CUSTOM_ERROR | 233L)
#define	D5_ERROR_CALC_COMMAND_AREA_OVERFLOW	(D5_CUSTOM_ERROR | 234L)
#define	D5_ERROR_CALC_SYNTAX_ERROR			(D5_CUSTOM_ERROR | 238L)
#define	D5_ERROR_SQL_DB						(D5_CUSTOM_ERROR | 239L)
#define	D5_ERROR_CALCPTR_STRING_AREA_OVERFLOW (D5_CUSTOM_ERROR | 240L)
#define	D5_CORBA_COMM_FAILURE				(D5_CUSTOM_ERROR | 242L)

#define	D5_ERROR_NOT_TREE					(D5_CUSTOM_ERROR | 250L)

#define	D5_ERROR_CALC_STR_STACK_OVERFLOW	(D5_CUSTOM_ERROR | 260L)
#define	D5_ERROR_CALC_NUM_STACK_OVERFLOW	(D5_CUSTOM_ERROR | 261L)

#define	D5_ERROR_CALC_PRG_STACK_OVERFLOW	(D5_CUSTOM_ERROR | 262L)
#define	D5_ERROR_CALC_CONVERT				(D5_CUSTOM_ERROR | 263L)
#define	D5_ERROR_CALC_STR_AREA_OVERFLOW		(D5_CUSTOM_ERROR | 264L)

#define	D5_INVALID_SHARED_OPERATION			(D5_CUSTOM_ERROR | 270L)
#define	D5_INVALID_SHARED_FILE				(D5_CUSTOM_ERROR | 271L)
#define	D5_INVALID_OS						(D5_CUSTOM_ERROR | 272L)
#define	D5_ERROR_SHARED_MEMORY				(D5_CUSTOM_ERROR | 273L)
#define	D5_CATALOG_PARSE_ERROR				(D5_CUSTOM_ERROR | 274L)
#define	D5_INVALID_DATA						(D5_CUSTOM_ERROR | 275L)
#define	D5_UNDEFINED_TYPE					(D5_CUSTOM_ERROR | 276L)
#define	D5_DATA_OVERFLOW					(D5_CUSTOM_ERROR | 277L)
#define	D5_ROW_SIZE_OVERFLOW				(D5_CUSTOM_ERROR | 278L)
#define	D5_MEM_OVERFLOW						(D5_CUSTOM_ERROR | 279L)
#define	D5_ERROR_ALREADY_EXIST				(D5_CUSTOM_ERROR | 280L)
#define	D5_ERROR_INVALID_DBCODE				(D5_CUSTOM_ERROR | 281L)
#define	D5_ERROR_INVALID_LOCALEID			(D5_CUSTOM_ERROR | 282L)
#define	D5_ERROR_INVALID_CHARACTER_FOUND	(D5_CUSTOM_ERROR | 283L)
#define	D5_ERROR_OUT_OF_RANGE				(D5_CUSTOM_ERROR | 284L)
#define D5_ERROR_INVALID_FILEVERSION		(D5_CUSTOM_ERROR | 285L)
#define D5_ERROR_FILEVERSION_NOT_EXIST		(D5_CUSTOM_ERROR | 286L)
#define D5_ERROR_NOT_REALTABLE				(D5_CUSTOM_ERROR | 287L)
#define	D5_ERROR_INVALID_ALIGNED_ADDRESS	(D5_CUSTOM_ERROR | 288L)
#define	D5_ERROR_INVALID_MEMORY_IO			(D5_CUSTOM_ERROR | 289L)

#define	D5_ERROR_QUERY_INTERNAL_ERROR			(D5_CUSTOM_ERROR | 290L)
#define	D5_ERROR_QUERY_SYNTAX_ERROR				(D5_CUSTOM_ERROR | 291L)
#define	D5_ERROR_QUERY_SEMANTIC_ERROR			(D5_CUSTOM_ERROR | 292L)
#define	D5_ERROR_QUERY_DATA_TYPE_MISMATCH		(D5_CUSTOM_ERROR | 293L)
#define	D5_ERROR_QUERY_TOO_LARGE_TEXT			(D5_CUSTOM_ERROR | 294L)
#define	D5_ERROR_EDITING_HSS_FILTER_NOT_ALLOWED	(D5_CUSTOM_ERROR | 310L)
#define D5_ERROR_TOO_LARGE_SUMMARY_ROW1			(D5_CUSTOM_ERROR | 320L)
#define D5_ERROR_TOO_LARGE_SUMMARY_ROW2			(D5_CUSTOM_ERROR | 321L)

#define	D5_ERROR_SUMMARY_IRREGULAR_DATA_DETECT	(D5_CUSTOM_ERROR | 322L)
#define	D5_ERROR_SUMMARY_DATA_NOT_DETECT		(D5_CUSTOM_ERROR | 323L)
#define	D5_ERROR_SUMMARY_NOT_NUM_MEASURE		(D5_CUSTOM_ERROR | 324L)
#define	D5_ERROR_SUMMARY_NOT_SUITABLE_TOTAL		(D5_CUSTOM_ERROR | 325L)

#define	D5_ERROR_SMP_THREAD_ABORTED				(D5_CUSTOM_ERROR | 350L)
#define D5_ERROR_UNKNOWN						(D5_CUSTOM_ERROR | 500L)
// 
#define D5_ERROR_NOT_IMPLEMENTED				(D5_CUSTOM_ERROR | 501L)
#define D5_ERROR_PASSWORD_FORMAT_ERROR			(D5_CUSTOM_ERROR | 701L)
#define D5_ERROR_PASSWORD_MAC_ADDRESS_MISMATCH	(D5_CUSTOM_ERROR | 702L)
#define D5_ERROR_PASSWORD_EXPIRE_DATE_MISMATCH	(D5_CUSTOM_ERROR | 703L)
#define D5_FILESIZE_OVERFLOW					(D5_CUSTOM_ERROR | 704L)

//	I/O
#define	D5_ERROR_LOG_FAILURE					(D5_CUSTOM_ERROR | 811L)



//ShmTable  Error Codes
//2009/08/25
#define D5_ERROR_D5TSHM_SEMAPHORE_REMOVED       (D5_CUSTOM_ERROR | 600L)
#define D5_ERROR_D5TSHM_SIGNAL_CAUGHT           (D5_CUSTOM_ERROR | 601L)
#define D5_ERROR_D5TSHM_RESOURCE_BUSY           (D5_CUSTOM_ERROR | 602L)
#define D5_ERROR_D5TSHM_SMCS_INIT               (D5_CUSTOM_ERROR | 603L)
#define D5_ERROR_D5TSHM_SMCS_READY              (D5_CUSTOM_ERROR | 604L)
#define D5_ERROR_D5TSHM_SMCS_ACTIVE             (D5_CUSTOM_ERROR | 605L)
#define D5_ERROR_D5TSHM_TOO_MANY_D5TSHM_TABLES  (D5_CUSTOM_ERROR | 606L)
#define D5_ERROR_D5TSHM_SHMTBL_INIT             (D5_CUSTOM_ERROR | 607L)
#define D5_ERROR_D5TSHM_SHMTBL_READY            (D5_CUSTOM_ERROR | 608L)
#define D5_ERROR_D5TSHM_SHMTBL_STANDBY          (D5_CUSTOM_ERROR | 609L)
#define D5_ERROR_D5TSHM_SHMTBL_REFERENCED       (D5_CUSTOM_ERROR | 610L)
#define D5_ERROR_D5TSHM_DUPLICATE_TABLE         (D5_CUSTOM_ERROR | 611L)
#define D5_ERROR_D5TSHM_INVALID_OS_PARAM        (D5_CUSTOM_ERROR | 612L)
#define D5_ERROR_D5TSHM_ALREADY_LOCKED          (D5_CUSTOM_ERROR | 613L)
#define D5_ERROR_D5TSHM_TOO_LARGE_D5T_FILE      (D5_CUSTOM_ERROR | 614L)
#define D5_WARNING_D5TSHM_SHMTBL_INIT           (D5_CUSTOM_ERROR | 615L)


#define	D5_ERROR_LOCK							(-2)
#define	D5_ERROR_TRIAL_LOCK						(-3)

#endif //  _D5ERROR_H
